// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type User struct {
	ID        int32
	Username  string
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
